=== CapiGurpi/Ejercicios-de-HTML/PR4/project.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="llibreta_contactes">
    <xs:complexType>
        <xs:sequence>

            <xs:element name="contacto" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="apellidos" type="xs:string"/>
                        <xs:element name="edad">
                            <xs:complexType mixed="true">
                                <xs:attribute name="mallor">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="si"/>
                                            <xs:enumeration value="no"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="dirección">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="calle" type="xs:string"/>
                                    <xs:element name="num_calle" type="xs:integer" minOccurs="0"/>
                                    <xs:element name="cod_postal" type="xs:string"/>
                                    <xs:element name="ciudad" type="xs:string"/>
                                </xs:sequence>
                                <xs:attribute name="domicilio">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="principal"/>
                                            <xs:enumeration value="secundario"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="dir_email" type="xs:string"/>
                        <xs:element name="telefons">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="fix" type="xs:string"/>
                                    <xs:element name="móvil" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="es_familiar">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="si"/>
                                <xs:enumeration value="no"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== CapiGurpi/Ejercicios-de-HTML/RA4/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
1 Crear un document en XML vàlid amb la informació d’un únic contacte.
1.2 Modela como a mínim la següent informació:
o Nom, cognoms
o telèfon fix, telèfon mòbil
1.3 Modifica el document afegir la següent informació:
o Edat
o direcció (carrer, codi postal, ciutat)
o direcció de email
1.4 Modifica el document per que pugui emmagatzemar 2 contactes.
1.5 Afegeix un atribut que ens indiqui si un contacte es un familiar o no, i si una direcció es el
domicili principal o no
-->

<llibreta_contactes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="project.xsd">
<contacto es_familiar = 'no'>
    <nombre> ROGER </nombre>
    <apellidos> SERRATS VICENTE </apellidos>
    <edad mallor = "si"> 18 </edad>
    <dirección domicilio = "principal">
        <calle> C/ RUBIÓ I BALAGUER</calle>
        
        <cod_postal> 08035 </cod_postal>
        <ciudad> BARCELONA </ciudad>
    </dirección>
    <dir_email> serri@gmail.com </dir_email>
    <telefons>
        <fix>   987 67 67 67</fix>
        <móvil> 611 47 19 77 </móvil>
    </telefons>
</contacto>
<contacto es_familiar = 'no'>
    <nombre> PAU </nombre>
    <apellidos> HERNANDEZ SADURNÍ </apellidos>
    <edad mallor = "si"> 18 </edad>
    <dirección domicilio = "secundario">
        <calle> CARRETERA DEL PRAT </calle>
        <num_calle> 46 </num_calle>
        <cod_postal> 08038 </cod_postal>
        <ciudad> BARCELONA </ciudad>
    </dirección>
    <dir_email> pauhernandezsadurni@gmail.com </dir_email>
    <telefons>
        <fix> 644 89 79 69 </fix>
        <móvil> 644 68 67 46</móvil>
    </telefons>
</contacto>
</llibreta_contactes>
