=== CapiGurpi/Ejercicios-de-HTML/RA3/project.dtd
<!ELEMENT llibreta_contactes (contacto+)>
<!ELEMENT contacto (nombre,apellidos,edad, direción*, dir.email, telefons)>
<!ATTLIST contacto es_familiar (si|no) #REQUIRED>
<!ELEMENT direción (calle,num_calle?, cod.postal, ciudad)>
<!ATTLIST direción domicilio CDATA #REQUIRED>
<!ELEMENT telefons (fix, móbil)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT num_calle (#PCDATA)>
<!ELEMENT cod.postal (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT dir.email (#PCDATA)>
<!ELEMENT fix (#PCDATA)>
<!ELEMENT móbil (#PCDATA)>

=== CapiGurpi/Ejercicios-de-HTML/PR3/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llibreta_contactes SYSTEM "project.dtd">
<!-- 
1 Crear un document en XML vàlid amb la informació d’un únic contacte.
1.2 Modela como a mínim la següent informació:
o Nom, cognoms
o telèfon fix, telèfon mòbil
1.3 Modifica el document afegir la següent informació:
o Edat
o direcció (carrer, codi postal, ciutat)
o direcció de email
1.4 Modifica el document per que pugui emmagatzemar 2 contactes.
1.5 Afegeix un atribut que ens indiqui si un contacte es un familiar o no, i si una direcció es el
domicili principal o no
-->

<llibreta_contactes>
<contacto es_familiar = 'no'>
    <nombre> ROGER </nombre>
    <apellidos> SERRATS VICENTE </apellidos>
    <edad> 18 </edad>
    <direción domicilio = "principal">
        <calle> C/ RUBIÓ I BALAGUER</calle>
        
        <cod.postal> 08035 </cod.postal>
        <ciudad> BARCELONA </ciudad>
    </direción>
    <dir.email> serri@gmail.com </dir.email>
    <telefons>
        <fix>   987 67 67 67</fix>
        <móbil> 611 47 19 77 </móbil>
    </telefons>
</contacto>
<contacto es_familiar = 'no'>
    <nombre> PAU </nombre>
    <apellidos> HERNANDEZ SADURNÍ </apellidos>
    <edad> 18 </edad>
    <direción domicilio = "secundario">
        <calle> CARRETERA DEL PRAT </calle>
        <num_calle> 46 </num_calle>
        <cod.postal> 08038 </cod.postal>
        <ciudad> BARCELONA </ciudad>
    </direción>
    <dir.email> pauhernandezsadurni@gmail.com </dir.email>
    <telefons>
        <fix> 644 89 79 69 </fix>
        <móbil> 644 68 67 46</móbil>
    </telefons>
</contacto>
</llibreta_contactes>
